name: 06. selfpractice

run-name: Deploy to ${{ inputs.env }} by @${{ github.actor }}

on:
  # push:
  #   - main
  workflow_dispatch:
    inputs:
      env:
        description: "enter env name"
        type: choice
        options:
        - stg
        - dev
        - prd
      branch:
        description: "enter your Branch name"
        type: string
        default: main

env:
  GITHUB_TOKEN: "SJDHIDHD"
  MOS_USER: "mosuser"
  MOS_PASWD: "mospaswd"
  
jobs:
  envprinttest:
    runs-on: ubuntu-latest
    env:
      USER: "user"
      PASSWORD: "password"
    outputs:
      result: ${{steps.example.outputs.TICKET}}
    steps: 
      - id: example
        run: |
          echo "TICKET=CHG8890">> "$GITHUB_OUTPUT"
      - name: envprint
        env:
          SECRET: "secret"
        run: |
          echo "MYNAME=PRIYA">> "$GITHUB_ENV"
          echo "HUSBAND=SURAJ">> "$GITHUB_ENV"
          # echo "$MYNAME"
          # echo "$HUSBAND"
   
      - name: printvariable
        run: |
          echo "$MYNAME"
          echo "$HUSBAND"
          echo "change number is ${{steps.example.outputs.TICKET}}"
          echo "${{env.GITHUB_TOKEN}}"
          echo "${{env.SECRET}}"
          
  build:
    runs-on: ubuntu-latest
    needs: envprinttest
    steps:
      - name: another step
        run: |
          echo "${{needs.envprinttest.outputs.result}}"
          echo "${{env.MOS_USER}}"
          echo "$MOS_USER"
          echo "${{env.SECRET}}"
  
      
      

      
      
  
