name: 06. selfpractice

on:
  # push:
  #   - main
  workflow_dispatch:
    inputs:
      env:
        description: "enter env name"
        type: choice
        options:
        - stg
        - dev
        - prd
      branch:
        description: "enter your Branch name"
        type: string
        default: main

jobs:
  envprinttest:
    runs-on: ubuntu-latest
    outputs:
      result: ${{steps.example.output.TICKET}}
    steps: 
      - id: example
        run: |
          echo "TICKET=CHG8890">> "$GITHUB_OUTPUT"
      - name: envprint
        run: |
          echo "MYNAME=PRIYA">> "$GITHUB_ENV"
          echo "HUSBAND=SURAJ">> "$GITHUB_ENV"
          # echo "$MYNAME"
          # echo "$HUSBAND"
   
      - name: printvariable
        run: |
          echo "$MYNAME"
          echo "$HUSBAND"
          echo "change number is ${{steps.example.outputs.TICKET}}"
          
  build:
    runs-on: ubuntu-latest
    needs: envprinttest
    steps:
      - name: another step
        run: |
          echo "${{needs.envprinttest.outputs.result}}"
  
      
      

      
      
  
